version: "2"
services:
  db:
    image: mysql:8.0
    restart: always
    expose:
      - 3306
    volumes:
    - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  app:
    restart: always
    container_name: ably_app
    image: ably-app:0.1
    build: ./
    ports:
      - 8080:8080

